# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: http://github.com/nlesc/python-template.git
copyright_holder: Nick Macey
email: nick.macey84@gmail.com
full_name: Nick Macey
github_organization: glimtoko
keywords: dessert,sweet
license: Apachev2
package_name: baklava
package_short_description: A sweet package
template_profile: minimum
version: 0.1.0
